"""Unified error object and error code definitions used across the whole system."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


ORCH_INVALID_INPUT = "ORCH_INVALID_INPUT"
ORCH_INVALID_TOOL_NAME = "ORCH_INVALID_TOOL_NAME"
ORCH_MISSING_AGENT_TYPE = "ORCH_MISSING_AGENT_TYPE"
ORCH_MISSING_USER_PROMPT = "ORCH_MISSING_USER_PROMPT"
ORCH_INVALID_AGENT_TYPE = "ORCH_INVALID_AGENT_TYPE"
ORCH_INVALID_STAGE_JUMP = "ORCH_INVALID_STAGE_JUMP"
ORCH_INVALID_MAIN_TURN = "ORCH_INVALID_MAIN_TURN"
ORCH_MAX_ITERATIONS_EXCEEDED = "ORCH_MAX_ITERATIONS_EXCEEDED"
ORCH_MAX_MAIN_TURNS_REACHED = "ORCH_MAX_MAIN_TURNS_REACHED"
ORCH_AGENT_TOOL_ERROR = "ORCH_AGENT_TOOL_ERROR"

EXPLORE_CONTEXT_INSUFFICIENT = "EXPLORE_CONTEXT_INSUFFICIENT"

PLAN_INSUFFICIENT_EVIDENCE = "PLAN_INSUFFICIENT_EVIDENCE"
PLAN_UNACTIONABLE_REPAIR_PLAN = "PLAN_UNACTIONABLE_REPAIR_PLAN"

EXECUTE_PATCH_APPLY_FAILED = "EXECUTE_PATCH_APPLY_FAILED"
EXECUTE_PLAN_DEVIATION = "EXECUTE_PLAN_DEVIATION"

VERIFY_TARGETED_TEST_FAILED = "VERIFY_TARGETED_TEST_FAILED"
VERIFY_SMOKE_TEST_FAILED = "VERIFY_SMOKE_TEST_FAILED"
VERIFY_TEST_ENVIRONMENT_ERROR = "VERIFY_TEST_ENVIRONMENT_ERROR"

TOOL_READ_LOG_FAILED = "TOOL_READ_LOG_FAILED"
TOOL_READ_CODE_FAILED = "TOOL_READ_CODE_FAILED"
TOOL_EDIT_CODE_FAILED = "TOOL_EDIT_CODE_FAILED"
TOOL_RUN_TEST_FAILED = "TOOL_RUN_TEST_FAILED"
TOOL_GIT_COMMIT_FAILED = "TOOL_GIT_COMMIT_FAILED"
TOOL_FEISHU_NOTIFY_FAILED = "TOOL_FEISHU_NOTIFY_FAILED"

ORCH_AGENT_TOOL_NOT_FOUND = "ORCH_AGENT_TOOL_NOT_FOUND"
ORCH_AGENT_TOOL_EXECUTION_ERROR = "ORCH_AGENT_TOOL_EXECUTION_ERROR"
ORCH_AGENT_MAX_TURNS_REACHED = "ORCH_AGENT_MAX_TURNS_REACHED"
ORCH_AGENT_FAILED = "ORCH_AGENT_FAILED"


@dataclass(slots=True)
class ErrorRecord:
    """Stable structured error object used across the whole system."""

    code: str
    message: str
    retryable: bool
    stage: str
    source: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def make_error(
    *,
    code: str,
    message: str,
    retryable: bool,
    stage: str,
    source: str,
) -> dict[str, Any]:
    """Create a normalized error dictionary."""

    return ErrorRecord(
        code=code,
        message=message,
        retryable=retryable,
        stage=stage,
        source=source,
    ).to_dict()
